### PR TITLE
[ISSUE-168] Fix issues with iBurn not compiling

### PR DESCRIPTION
**Pull request by bricepollock**
* iBurn submodule was referencing private repositiory iBurn-Data-Private >> Replaced with iBurn-Data submodule
* `iBurn-2023.zip` is missing >> replaced to include `iBurn-2022.zip` instead
* `GoogleService-Info.plist` is missing >> Included `GoogleService-Info+test.plist` and instructions to temp move into place
* Compiler issue with new authorization state mapping to `PermissionStatus` enum

### CODE REVIEW

**Comment by chrisballinger** [comment]
Thanks! The 2023 data is public now so I can push up some of what you're missing here

**Comment by bricepollock** [comment]
@chrisballinger happy to help modernize and transition from the ten year old dependancies as a next step. Going to close this PR for now due to inactivity.

**Comment by chrisballinger** [comment]
Would definitely love some more help with maintenance! Will reach out via email

**Comment by bricepollock** [comment]
Landing this into my fork

**Comment by chrisballinger** [comment]
I just pushed a bunch of changes and dependency updates. My changes will conflict with your original PR but would be open to merging your readme changes and temp GoogleService-Info.plist!

The MapLibre 6.0 update was a real pain, but the worth it for the new Metal support: https://maplibre.org/news/2024-01-19-metal-support-for-maplibre-native-ios-is-here/

**Comment by bricepollock** [comment]
Thanks! Updated README and temp GoogleService-Info.plist, might be helpful for getting someone new setup.

**Pull request closed without merging**
